### ISSUE TITLE
Not generating any graves, with error

### ISSUE THREAD

**Issue by Wenoc** [NightKosh/Gravestone-mod-Graves#204]
[00:58:51] [Server thread/INFO] [OpenMods/]: openblocks.common.PlayerInventoryStore.onPlayerDeath(PlayerInventoryStore.java:302): Storing post-mortem inventory into /home/simon/owlcraft/./world/data/inventory-malar-2016-04-03_00.58.51-death-0.dat. It can be restored with command '/ob_inventory restore malar malar-2016-04-03_00.58.51-death-0'
[00:58:51] [Server thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.event.entity.living.LivingDeathEvent@26114e01:
java.lang.NullPointerException
        at java.util.ArrayList.addAll(ArrayList.java:577) ~[?:1.8.0_77]
        at nightkosh.gravestone.helper.GraveGenerationHelper.createPlayerGrave(GraveGenerationHelper.java:117) ~[GraveGenerationHelper.class:?]
        at nightkosh.gravestone.core.event.EventsHandler.onEntityLivingDeath(EventsHandler.java:43) ~[EventsHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_730_EventsHandler_onEntityLivingDeath_LivingDeathEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
        at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:475) [ForgeHooks.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:429) [lf.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:853) [pr.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1047) [wn.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:531) [lf.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:237) [pr.class:?]
        at net.minecraft.entity.Entity.func_70071_h_(Entity.java:279) [pk.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1564) [pr.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:283) [wn.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:328) [lf.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:326) [lm.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:126) [ip.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:8) [ip.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fh$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_77]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_77]
        at net.minecraft.util.Util.func_181617_a(SourceFile:44) [g.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
[00:58:51] [Server thread/ERROR] [FML/]: Index: 7 Listeners:
[00:58:51] [Server thread/ERROR] [FML/]: 0: HIGHEST
[00:58:51] [Server thread/ERROR] [FML/]: 1: ASM: com.rwtema.extrautils2.items.ItemGoldenLasso@14fc8d76 cursedLassoAbsorb(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[00:58:51] [Server thread/ERROR] [FML/]: 2: ASM: WayofTime.bloodmagic.util.handler.EventHandler@6622f7e4 onEntityDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[00:58:51] [Server thread/ERROR] [FML/]: 3: ASM: vazkii.botania.common.item.equipment.bauble.ItemGoldenLaurel@3cd7ab1b onPlayerDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[00:58:51] [Server thread/ERROR] [FML/]: 4: ASM: gr8pefish.ironbackpacks.events.ForgeEventHandler@6cbfab3e onDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[00:58:51] [Server thread/ERROR] [FML/]: 5: HIGH
[00:58:51] [Server thread/ERROR] [FML/]: 6: ASM: openblocks.common.PlayerInventoryStore@56188063 onPlayerDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[00:58:51] [Server thread/ERROR] [FML/]: 7: ASM: nightkosh.gravestone.core.event.EventsHandler@158948af onEntityLivingDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[00:58:51] [Server thread/ERROR] [FML/]: 8: NORMAL
[00:58:51] [Server thread/ERROR] [FML/]: 9: ASM: thaumcraft.common.lib.events.EntityEvents@6e4ee6c livingDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[00:58:51] [Server thread/ERROR] [FML/]: 10: ASM: com.DavidM1A2.AfraidOfTheDark.common.handler.PlayerController@52f053fb onLivingDeathEvent(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[00:58:51] [Server thread/ERROR] [FML/]: 11: ASM: vazkii.botania.common.brew.potion.PotionSoulCross@334c52ce onEntityKill(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[00:58:51] [Server thread/ERROR] [FML/]: 12: ASM: org.cyclops.evilcraft.event.LivingDeathEventHook@3f48a6ec onLivingDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[00:58:51] [Server thread/ERROR] [FML/]: 13: ASM: latmod.ftbu.mod.handlers.FTBUPlayerEventHandler@3d4e0fd5 onPlayerDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[00:58:51] [Server thread/ERROR] [FML/]: 14: ASM: k4unl.minecraft.Hydraulicraft.events.EventHelper@4fd06655 onDeathEvent(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[00:58:51] [Server thread/ERROR] [FML/]: 15: ASM: lumien.randomthings.handler.RTEventHandler@a067b38 livingDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[00:58:51] [Server thread/ERROR] [FML/]: 16: ASM: pixlepix.auracascade.main.event.EventHandler@24c692b7 onPlayerDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[00:58:51] [Server thread/ERROR] [FML/]: 17: ASM: me.ichun.mods.deathcounter.common.core.DeathCounter@4bb567e0 onDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[00:58:51] [Server thread/ERROR] [FML/]: 18: ASM: com.enderio.core.common.handlers.XPBoostHandler@e4ee8cc handleEntityKill(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[00:58:51] [Server thread/ERROR] [FML/]: 19: ASM: com.inventorypets.DeathSaveHandler@42897435 notifyAttack(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[00:58:51] [Server thread/ERROR] [FML/]: 20: ASM: tb.common.enchantment.EnchantmentHandler@2ccab4e9 onMobDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[00:58:51] [Server thread/ERROR] [FML/]: 21: LOWEST
[00:58:51] [Server thread/ERROR] [FML/]: 22: ASM: com.rwtema.extrautils2.eventhandlers.RevengeHandler@617e33fe onLivingDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[00:58:51] [Server thread/ERROR] [FML/]: 23: ASM: emoniph.intangible.EventHandlers@457400f5 onLivingDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V

Probably a compatibility issue. It's not generating graves, and all items are lost. Only XP seems to be dropped.

**Comment by Wenoc** [comment]
Trying w/o openblocks, that seems to be 1.8.0 in this install.

**Comment by NightKosh** [comment]
Which version of minecraft you used? 1.8?
As for temporal fix - you can disable player's graves generation in my mod...

**Comment by Wenoc** [comment]
1.8.9 actually. When I have the time, I'll check if I can get it to work in another way. I'll inform you if I can identify the problem. I'm a bit busy this week though. Perhaps on the weekend.

**Comment by NightKosh** [comment]
It fixed for Minecraft 1.10.2 Is 1.8 version required?
