### ISSUE TITLE
gravestone mod crash when die (1.8.9)

### ISSUE THREAD

**Issue by Sasikaa** [NightKosh/Gravestone-mod-Graves#205]
This modpack is crashing with your mod:
ILabs TNG modpack
When i died, the game crashing.
This is my crash log:

http://pastebin.com/AhRTPbfU

**Comment by NightKosh** [comment]
GraveStone-1.8.9-Graves-1.0.0.jar
`
java.lang.NullPointerException: Ticking entity
    at java.util.ArrayList.addAll(Unknown Source)
    at nightkosh.gravestone.helper.GraveGenerationHelper.createPlayerGrave(GraveGenerationHelper.java:117)
    at nightkosh.gravestone.core.event.EventsHandler.onEntityLivingDeath(EventsHandler.java:43)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_998_EventsHandler_onEntityLivingDeath_LivingDeathEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:475)
    at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:429)
    at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:853)
    at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1047)
    at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:531)
    at net.minecraft.entity.projectile.EntityArrow.func_70071_h_(SourceFile:286)
    at net.minecraft.world.World.func_72866_a(World.java:1862)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:700)
    at net.minecraft.world.World.func_72870_g(World.java:1831)
    at net.minecraft.world.World.func_72939_s(World.java:1663)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Unknown Source)
 `

**Comment by NightKosh** [comment]
Fixed for minecraft 1.10.2. Is 1.8.9 version required?
