### ISSUE TITLE
NPE on death: Ticking entity

### ISSUE THREAD

**Issue by Zeevian** [NightKosh/Gravestone-mod-Graves#220]
Wasn't holding anything in my hand, was shot by a skeleton to death, and caused a crash to NullPointerException: Ticking Entity.
[crash-2017-04-21_17.32.12-server.txt](https://github.com/NightKosh/Gravestone-mod-Graves/files/948363/crash-2017-04-21_17.32.12-server.txt)

**Comment by NightKosh** [comment]
```
java.lang.NullPointerException: Ticking entity
	at java.util.ArrayList.addAll(ArrayList.java:577)
	at nightkosh.gravestone.helper.GraveGenerationHelper.createPlayerGrave(GraveGenerationHelper.java:121)
	at nightkosh.gravestone.core.event.EventsHandler.onEntityLivingDeath(EventsHandler.java:43)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_978_EventsHandler_onEntityLivingDeath_LivingDeathEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:509)
	at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:439)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:970)
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1022)
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:543)
	at net.minecraft.entity.projectile.EntityArrow.func_184549_a(SourceFile:337)
	at net.minecraft.entity.projectile.EntityArrow.func_70071_h_(SourceFile:254)
	at net.minecraft.entity.projectile.EntityTippedArrow.func_70071_h_(EntityTippedArrow.java:85)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
```
Minecraft 1.10.2
Forge 12.18.3.2281

**Comment by NightKosh** [comment]
There is a compatibility problem with EnderIO.
