### ISSUE TITLE
tconstruct NoClassDefFoundError crash when creating grave

### ISSUE THREAD

**Issue by Barteks2x** [NightKosh/Gravestone-mod-Graves#231]
[crash-2017-07-01_19.59.20-server.txt](https://github.com/NightKosh/Gravestone-mod-Graves/files/1117325/crash-2017-07-01_19.59.20-server.txt)

**Comment by NightKosh** [comment]
```

java.lang.NoClassDefFoundError: tconstruct/api/TConstructAPI
	at nightkosh.gravestone.core.compatibility.CompatibilityTinkerConstruct.lambda$new$5(CompatibilityTinkerConstruct.java:30)
	at nightkosh.gravestone.helper.GraveGenerationHelper.createPlayerGrave(GraveGenerationHelper.java:120)
	at nightkosh.gravestone.core.event.EventsHandler.onEntityLivingDeath(EventsHandler.java:43)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_107_EventsHandler_onEntityLivingDeath_LivingDeathEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:547)
	at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:465)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:990)
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1040)
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:571)
	at net.minecraft.entity.projectile.EntityArrow.func_184549_a(SourceFile:339)
	at net.minecraft.entity.projectile.EntityArrow.func_70071_h_(SourceFile:256)
	at net.minecraft.entity.projectile.EntityTippedArrow.func_70071_h_(SourceFile:98)
	at net.minecraft.world.World.func_72866_a(World.java:1965)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1748)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: tconstruct.api.TConstructAPI
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 24 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 26 more
```

**Comment by NightKosh** [comment]
Tinker construct API missed. I'm not sure what happens, but I can't find it in its repository. I need some time to inspect this problem. So you could set "StoreTinkerConstructItems" to "false" in configuration file. It should prevent game crash(but items from tinker construct slots will not be stored in the grave). This is a temporary solution.

**Comment by Barteks2x** [comment]
As a temporary solution I just used a different graves mod.

**Comment by UniaRethran** [comment]
Have you found a solution for this problem?  Error: java.lang.NoClassDefFoundError: nightkosh/gravestone/helper/IFog

**Comment by NightKosh** [comment]
@UniaRethran Could you please provide a crash log?
