### ISSUE TITLE
[1.12] Client Crash on Death (compatibility with Backpack)

### ISSUE THREAD

**Issue by yotthani** [NightKosh/Gravestone-mod-Graves#274]
Version: 
gravestone@1.0.16, gravestone-extended@1.3.0b7, backpack@3.0.2

Client crash when died with backback

Log:
"[10:29:11] [Server thread/ERROR] [gravestone]: Can't save Backpacks items!!!
[10:29:11] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:48]: java.lang.ClassNotFoundException: de.eydamos.backpack.saves.PlayerSave
[10:29:11] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:48]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[10:29:11] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:48]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[10:29:11] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:48]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[10:29:11] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:48]: 	at java.lang.Class.forName0(Native Method)
[10:29:11] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:48]: 	at java.lang.Class.forName(Class.java:264)
[10:29:11] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:48]: 	at nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod.lambda$new$0(CompatibilityBackpacksMod.java:29)
[10:29:11] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:48]: 	at nightkosh.gravestone.helper.GraveGenerationHelper.createPlayerGrave(GraveGenerationHelper.java:135)
[10:29:11] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:48]: 	at nightkosh.gravestone.core.event.EventsHandler.onEntityLivingDeath(EventsHandler.java:43)
[10:29:11] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:48]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1458_EventsHandler_onEntityLivingDeath_LivingDeathEvent.invoke(.dynamic)
[10:29:11] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:48]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[10:29:11] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:48]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
[10:29:11] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:48]: 	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:600)
[10:29:11] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:48]: 	at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:474)
[10:29:11] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:48]: 	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1014)
[10:29:11] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:48]: 	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1038)
[10:29:11] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:48]: 	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:645)
[10:29:11] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:48]: 	at micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP.func_70097_a(GCEntityPlayerMP.java:68)
[10:29:11] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:48]: 	at net.minecraft.entity.item.EntityEnderPearl.func_70184_a(EntityEnderPearl.java:119)
[10:29:11] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:48]: 	at net.minecraft.entity.projectile.EntityThrowable.func_70071_h_(EntityThrowable.java:249)
[10:29:11] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:48]: 	at net.minecraft.entity.item.EntityEnderPearl.func_70071_h_(EntityEnderPearl.java:143)
[10:29:11] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:48]: 	at net.minecraft.world.World.func_72866_a(World.java:1990)
[10:29:11] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:48]: 	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
[10:29:11] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:48]: 	at net.minecraft.world.World.func_72870_g(World.java:1952)
[10:29:11] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:48]: 	at net.minecraft.world.World.func_72939_s(World.java:1756)
[10:29:11] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:48]: 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
[10:29:11] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:48]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
[10:29:11] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:48]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
[10:29:11] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:48]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[10:29:11] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:48]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[10:29:11] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:48]: 	at java.lang.Thread.run(Thread.java:748)
[10:29:11] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.NullPointerException"

**Comment by NightKosh** [comment]
Hello. I'll try to fix it in nearest time. 
As a temporal solution you can disable "Backpack" compatibility module by set "StoreBackpacksItems" to "false".

**Comment by yotthani** [comment]
thx.. i have already changed the config to false .. but wanted to give you the hint that there is somthing wrong ;)

**Comment by Psy-Virus** [comment]
Still getting an error.
Running your mod @ 1.1.0 and Backpacks @ 3.0.2

```
[17:18:57] [Server thread/ERROR] [gravestone]: Can't save Backpacks items!!!
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: java.lang.NoSuchMethodException: de.eydamos.backpack.data.PlayerSave.removeStackFromSlot(int)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at java.lang.Class.getDeclaredMethod(Class.java:2130)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod.lambda$new$0(CompatibilityBackpacksMod.java:36)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod$$Lambda$664/2063893033.addItems(Unknown Source)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at nightkosh.gravestone.helper.GraveGenerationHelper.createPlayerGrave(GraveGenerationHelper.java:135)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at nightkosh.gravestone.core.event.EventsHandler.onEntityLivingDeath(EventsHandler.java:44)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_600_EventsHandler_onEntityLivingDeath_LivingDeathEvent.invoke(.dynamic)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:601)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:474)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1016)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1038)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:645)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at drzhark.mocreatures.entity.MoCEntityMob.func_70652_k(MoCEntityMob.java:548)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at drzhark.mocreatures.entity.monster.MoCEntityManticore.func_70652_k(MoCEntityManticore.java:128)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at net.minecraft.entity.ai.EntityAIAttackMelee.func_190102_a(EntityAIAttackMelee.java:178)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at net.minecraft.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:167)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:888)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2352)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at drzhark.mocreatures.entity.MoCEntityMob.func_70636_d(MoCEntityMob.java:283)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at drzhark.mocreatures.entity.monster.MoCEntityManticore.func_70636_d(MoCEntityManticore.java:210)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2172)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at drzhark.mocreatures.entity.monster.MoCEntityManticore.func_70071_h_(MoCEntityManticore.java:192)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at net.minecraft.world.World.func_72866_a(World.java:1990)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at net.minecraft.world.World.func_72870_g(World.java:1952)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at net.minecraft.world.World.func_72939_s(World.java:1756)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[17:18:57] [Server thread/INFO] [STDERR]: [nightkosh.gravestone.core.compatibility.CompatibilityBackpacksMod:lambda$new$0:50]: 	at java.lang.Thread.run(Thread.java:745)
[17:18:57] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: PsyVirus was slain by Manticore
[17:18:57] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] PsyVirus was slain by Manticore
```

**Comment by Psy-Virus** [comment]
Btw. I saw that the backpack got dropped after death and my dead body collected it. I saw it in the respawn screen in my hotbar.

**Comment by Psy-Virus** [comment]
Oh, my dead body collected it because I had the Magnet Mode of NEI enabled. After I disabled it, the backpack was hovering besides the grave, what's still not perfect. Especially if you die over lava...

**Comment by Psy-Virus** [comment]
Tested and works so far. Thanks, kind sir!

I know you probably don't want to. But would you also be so kind and give the 1.10.2 and 1.7.10 Versions a last *good will* update? They had all the same error, as far as I remember.

I wonder that no one has ever mentioned it... I mean, me neither *shame on me*

:)
