### ISSUE TITLE
Client crash on death, may a facing Problem?

### ISSUE THREAD

**Issue by Jergeric** [NightKosh/Gravestone-mod-Graves#287]
sorry, I have no idea if it's the Gravestone Mod or Dynamic Surroundings :/

https://paste.dimdev.org/uxifanadem.mccrash

**Comment by NightKosh** [comment]
```
java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.getValue(BlockStateContainer.java:209)
    at nightkosh.gravestone.block.BlockGraveStone.getBoundingBox(BlockGraveStone.java:170)
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.getBoundingBox(BlockStateContainer.java:468)
    at net.minecraft.block.Block.collisionRayTrace(Block.java:631)
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.collisionRayTrace(BlockStateContainer.java:473)
    at org.blockartistry.lib.math.RayTrace.rayTraceBlocks(RayTrace.java:271)
    at org.blockartistry.lib.math.RayTrace.trace(RayTrace.java:76)
    at org.blockartistry.DynSurround.client.handlers.effects.EntitySwingEffect.update(EntitySwingEffect.java:80)
    at org.blockartistry.lib.effects.EntityEffectHandler.update(EntityEffectHandler.java:108)
    at org.blockartistry.DynSurround.client.handlers.FxHandler.lambda$static$1(FxHandler.java:93)
    at org.blockartistry.lib.collections.CollectionUtils.removeIf(CollectionUtils.java:42)
    at org.blockartistry.DynSurround.client.handlers.FxHandler.process(FxHandler.java:125)
    at org.blockartistry.DynSurround.client.handlers.EffectManager.onTick(EffectManager.java:173)
    at org.blockartistry.DynSurround.client.handlers.EffectManager.clientTick(EffectManager.java:183)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_223_EffectManager_clientTick_ClientTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1707)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1097)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3940)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by NightKosh** [comment]
I'm wondering is this problem stable or not? Did your game crashed just once or it can not be reloaded now?

**Comment by Jergeric** [comment]
You can log in again after that but it happens more often, today already 7 times

> Time: 2018-10-09 18:00:45 CEST
Description: Unexpected error
java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.getValue(BlockStateContainer.java:209)
    at nightkosh.gravestone.block.BlockGraveStone.getBoundingBox(BlockGraveStone.java:170)
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.getBoundingBox(BlockStateContainer.java:468)
    at net.minecraft.block.Block.collisionRayTrace(Block.java:631)
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.collisionRayTrace(BlockStateContainer.java:473)
    at org.blockartistry.lib.math.RayTrace.rayTraceBlocks(RayTrace.java:271)
    at org.blockartistry.lib.math.RayTrace.trace(RayTrace.java:76)
    at org.blockartistry.DynSurround.client.handlers.effects.EntitySwingEffect.update(EntitySwingEffect.java:80)
    at org.blockartistry.lib.effects.EntityEffectHandler.update(EntityEffectHandler.java:108)
    at org.blockartistry.DynSurround.client.handlers.FxHandler.lambda$static$1(FxHandler.java:93)
    at org.blockartistry.lib.collections.CollectionUtils.removeIf(CollectionUtils.java:42)
    at org.blockartistry.DynSurround.client.handlers.FxHandler.process(FxHandler.java:125)
    at org.blockartistry.DynSurround.client.handlers.EffectManager.onTick(EffectManager.java:173)
    at org.blockartistry.DynSurround.client.handlers.EffectManager.clientTick(EffectManager.java:183)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_223_EffectManager_clientTick_ClientTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1707)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1097)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3940)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by NightKosh** [comment]
Do you have any suggestions what was go wrong? Did it happened with player grave? It looks like game tried to get grave block but it got block of Air instead.

**Comment by NightKosh** [comment]
The same issue #263
